# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68b28677d468987353577b85c003bb483e446c8146869fedcd19d8feb76a84c8048cf581d08ee1503e8effad9c83360767e6a6f0640751c7eefde600613b786a

test:
  secret_key_base: 2df08832f5c2d4032a86935ea85d48e84df4b4200d4591dace5789fc5b3c96936d8cf6bfe0ece976af70e3039fd7f5693aabadf1abc54076a65485e8809d7376

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
